---
stages:
  - build
  - scan

variables:
  HTTPS_PROXY: "${HTTPS_PROXY}"
  HTTP_PROXY: "${HTTP_PROXY}"
  NO_PROXY: "${NO_PROXY}"
  http_proxy: "${HTTP_PROXY}"
  https_proxy: "${HTTPS_PROXY}"
  no_proxy: "${NO_PROXY}"

before_script:
  - git config --global http.proxy "${HTTP_PROXY}"
  - git config --global https.proxy "${HTTPS_PROXY}"
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_SERVER}".insteadOf "https://${GITLAB_SERVER}"
  - cd $CI_PROJECT_DIR

compile:
  stage: build
  image: golang:1.14
  tags:
    - go
  script:
    - make -C isecl-k8s-controller isecl-k8s-controller
    - make -C isecl-k8s-scheduler isecl-k8s-scheduler

Stylechecker:
    stage: scan
    only:
      - merge_requests
    image: golang:1.14
    tags:
       - go
    script:
       - gofmt -l .
       - |
             if [ "$(gofmt -l . | wc -l)"  -gt 0 ]; then
                    exit 1
             fi
       
snykscan:
  stage: scan
  only:
    - merge_requests
  tags:
    - snyk-scan-k8s
  allow_failure: true
  before_script:
    - export CGO_CFLAGS_ALLOW="-f.*" GOOS=linux GOSUMDB=off GOPROXY=direct
    - snyk config set endpoint=$SNYK_URL
    - snyk auth $AUTH_TOKEN
    - snyk config set api=$SYNK_API_TOKEN
    - snyk config set org=$ORG_NAME
  script:
    - snyk test --insecure --all-projects --json-file-output=snyc-scan.json
  artifacts:
    paths:
      - snyc-scan.json




checkmarx:
  stage: scan
  allow_failure: true
  only:
     - merge_requests
  services:
      - docker:dind
  image:
    name: ${DOCKER_REGISTRY_SERVER}:${DOCKER_REGISTRY_PORT}/checkmarx:isecl
    entrypoint: ['']
  tags:
    - docker-checkmarx
  script:
    - cat ${CX_FLOW_CONFIG} > application.yml
    - |
      if [ "$CI_PIPELINE_SOURCE" == "merge_request_event" ]; then 
        java -jar /app/cx-flow.jar --spring.config.location=./application.yml \
          --scan \
          --cx-team="${CHECKMARX_TEAM}" \
          --cx-project="${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}" \
          --app="${CI_PROJECT_NAME}" \
          --project-id=${CI_PROJECT_ID} \
          --merge-id=${CI_MERGE_REQUEST_IID} \
          --bug-tracker=GITLABMERGE \
          --cx-flow.break-build=false \
          --f=.
      else
        java -jar /app/cx-flow.jar --spring.config.location=./application.yml \
          --scan \
          --cx-team="${CHECKMARX_TEAM}" \
          --cx-project="${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}" \
          --app="${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}" \
          --branch="${CI_COMMIT_REF_NAME}" \
          --repo-name="${CI_PROJECT_NAME}" \
          --namespace="${CI_PROJECT_NAMESPACE##*/}" \
          --cx-flow.break-build=false \
          --f=.
      fi