#/*
# * Copyright (C) 2020 Intel Corporation
# * SPDX-License-Identifier: BSD-3-Clause
# */

---
apiVersion: v1
kind: Namespace
metadata:
  name: isecl

--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: isecl-scheduler
    env: demo
  name: isecl-scheduler-svc
  namespace: isecl
spec: 
  ports: 
    - 
      nodePort: 30888
      port: 8888
      targetPort: 8888
  selector: 
    app: isecl-scheduler
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: isecl-scheduler
  name: isecl-scheduler
  namespace: isecl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isecl-scheduler
  template:
    metadata:
      labels:
        app: isecl-scheduler
      name: isecl-scheduler
    spec:
      securityContext:
        fsGroup: 1001
      initContainers:
        - image: busybox:latest
          name: chmod-pg-data
          command:
            - /bin/chown
            - -R
            - "1001"
            - /var/log/isecl-k8s-extensions
          volumeMounts:
            - name: scheduler-log
              mountPath: /var/log/isecl-k8s-extensions
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                 -
                  key: node-role.kubernetes.io/master
                  operator: Exists
      containers:
        - name: isecl-scheduler
          image: isecl/k8s-scheduler
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
          env:
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: TAG_PREFIX
              value: "isecl."
            - name: PORT
              value: "8888"
            - name: IHUB_PUBLIC_KEY_FILE_PATH
              value: "/opt/isecl-k8s-extensions/ihub_public_key.pem"
            - name: TLS_CERT_PATH
              value: "/opt/isecl-k8s-extensions/server.crt"
            - name: TLS_KEY_PATH
              value: "/opt/isecl-k8s-extensions/server.key"
          volumeMounts:
          - mountPath: /var/log/isecl-k8s-extensions
            name: scheduler-log
          - name: scheduler-certs
            mountPath: /opt/isecl-k8s-extensions/
            readOnly: true
      volumes:
        - hostPath:
            path: /var/log/isecl-k8s-extensions
            type: DirectoryOrCreate
          name: scheduler-log
        - name: scheduler-certs
          secret:
            secretName: scheduler-certs
            defaultMode: 0640

